trigger:
  - main

pool: default

steps:
  - task: CmdLine@2
    inputs:
      script: |
        echo  '$(System.DefaultWorkingDirectory)'
        dir
    displayName: Show working directory

  - task: NodeTool@0
    inputs:
      versionSpec: "22.x"
    displayName: "Install Node.js"

  - script: npm install
    displayName: "Install dependencies"

  - script: |
      call npx newman run collections/Hoppscotch.postman_collection.json
      call npx newman run "collections/JSON Placeholder.postman_collection.json" -e environments/Scratchpad.postman_environment.json
    displayName: "Run integration tests"
